[tool.mypy]
python_version = "3.10"
files = "**/*.py"
explicit_package_bases = true

[tool.isort]
profile = "black"
line_length = 120
combine_as_imports = true
src_paths = ["src", "tests"]

[tool.black]
line_length = 120

[tool.pytest.ini_options]
pythonpath = ["."]
