# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Linting and tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python3.10 -m venv .venv --prompt="venv-cli"
        . .venv/bin/activate
        python -m pip install --require-virtualenv --upgrade pip
        python -m pip install --require-virtualenv -r dev-requirements.txt
    - name: Check linting/formatting
      run: |
        . .venv/bin/activate
        python -m isort --check .
        python -m black --config pyproject.toml --check .
        python -m mypy --config-file pyproject.toml
    - name: Test with pytest
      run: |
        . .venv/bin/activate
        python -m pytest -n auto .
